// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gdopicetwkrzihvwikwu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imdkb3BpY2V0d2tyemlodndpa3d1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgzMDA1NjcsImV4cCI6MjA2Mzg3NjU2N30.9L5UKJV8XGXi24_zURPz1blEj5qzwg3-Di3Z7L0me-0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);